clone:
  default:
    image: alpine
    commands:
      - echo $DRONE_REPO_PRIVATE
      - cat /root/.netrc

pipeine:
  build:
    image: alpine
    commands:
      - echo hello
    test:
      image: alpine
      commands: echo $DRONE_SECRET
